name: DataFlexing
title: DataFlexing | El Blog de los Datos 
description: Blog con el fin de compartir el conocimiento e impulsarme a mi mismo a aprender más.
tags:
  - blog
  - Data science
  - Programación
  - Hacking
  - Redes
show_hero: true
menu:
  - title: Home
    url: /
  - title: Acerca de mí
    url: /about
  - title: Contacto
    url: /contact
  - title: Inicio
    url: /feed.xml
email: eliancanul133@gmail.com
# See: https://disqus.com/
disqus_username: eliancanul
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xwkybaok
